### ISSUE TITLE
Put together a roadmap from prototype to production for FNS

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/data-federation-project#177]
- [ ] Schedule meeting to discuss
- [ ] Collaborate to put together a list of items that need to happen between now and the tool being in production 
- [ ] Identify and note any contingencies
- [ ] Share with FNS

**Comment by juliaklindpaintner** [comment]
Drafted doc for FNS PWS and started outlining the roadmap [here](https://docs.google.com/document/d/17XIcNH7fimn_IiNwtVAWzgOG7PzA0V3ltvIsBaJtVVY/edit#)
